/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Products: () => import('#controllers/products_controller'),
  StoreContoller: () => import('#controllers/store_contoller'),
  Users: () => import('#controllers/users_controller'),
}
